CREATE DATABASE VIVAPATIENTS
USE VIVAPATIENTS
CREATE TABLE Patients(
 PatientId INT IDENTITY(1,1) PRIMARY KEY,
 DocumentType VARCHAR(10) NOT NULL,
 DocumentNumber NVARCHAR(20) NOT NULL UNIQUE,
 FirstName NVARCHAR(80) NOT NULL,
 LastName NVARCHAR(80) NOT NULL,
 BirthDate DATE NOT NULL,
 PhoneNumber NVARCHAR(20) NULL,
 Email NVARCHAR(120) NULL,
 CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);